### ISSUE TITLE
Bug: Signup does nothing

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-Ardi83#1]
Your signup is not working, and why in the world is the password field in clear text?

<img width="274" alt="Screenshot 2019-03-22 at 07 32 49" src="https://user-images.githubusercontent.com/343422/54804773-fa411f80-4c74-11e9-88af-4db4258366c4.png">

**Comment by Ardi83** [comment]
now its work , login , logout is work , but i dont know why reset password doesnt work , also profile route is almost usless . thanks for comment
