### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-Ardi83#2]
@Ardi83 you've taken quite a few liberties with your application design and I have to say it's not very clear, at all, how to do anything on your recipe site.

I also saw your comment in the README.

Here are the things I need you to implement in order for me to pass the grade:

- [x]  Kunna skrolla genom över förslag på recept
- [x]  Kunna filtrera förslagen av recept på måltidstyp och allergener (this view: http://ardinasiri.chas.academy/recipe is not actually filtering anything, or perhaps you're missing data in your API. Either way - it doesn't work as I've described here).
    - [x]  Förrätt, huvudrätt eller dessert
    - [x]  Allergener och dietval (t.ex. gluten, nötter, vegetarian osv.)
- [x]  Kunna klicka på ett recept för att se dess information (egen route) (you show information in a modal, it needs to be a separate route)
- [ ]  Kunna spara receptet i en lista (redigera/ta bort från lista) (this I can't do at all)

**Comment by Ardi83** [comment]
now ive added search through meal name , and filtering by categories, also if you login have access to delete or edit or add item , (I realy realy hate cors policy , its tooks my time almost 2 days)

**Comment by axeberg** [comment]
Re-opening this since you are still missing the saving of recipes to lists, which is kind of the point of this assignment.

**Comment by Ardi83** [comment]
Favorite list added to the App
