### ISSUE TITLE
Bug: Ununsed and not functioning links in the navigation (footer and header)

### ISSUE THREAD

**Issue by axeberg** [chas-academy/06-recipe-app-frontend-Ardi83#4]
![image](https://user-images.githubusercontent.com/343422/54805059-0c6f8d80-4c76-11e9-9a99-4b45070fe063.png)

What is the point of "Link", "Categories" and "Disabled" here? They seemingly do nothing.

Same goes for this in the footer:

![image](https://user-images.githubusercontent.com/343422/54805097-27420200-4c76-11e9-9c64-2295bfcc86a8.png)

I would urge you to remove all non-functioning stuff.

**Comment by Ardi83** [comment]
unused link deleted
